name: eslint

on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: yarn install
        run: yarn install

      - name: eslint-review
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          workdir: ./frontend
          eslint_flags: "src/**/{*.ts,*.tsx}"

      - name: eslint
        run: cd ./frontend/; yarn lint
